using Humanizer;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace VenusRootLoader.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class VenusLeafRegistryApiSourceGenerator : IIncrementalGenerator
{
    private record LeafTypeInfo
    {
        public required string LeafTypeName { get; init; }
        public required string LeafTypeDisplayString { get; init; }
        public required string? OrderAfterTypeName { get; init; }
        public required bool WithRegisterMethod { get; init; }
    }

    private record LeafInitializationMethodInfo
    {
        public required string LeafTypeName { get; init; }
        public required string LeafTypeDisplayString { get; init; }
        public required string MethodName { get; init; }
        public required string MethodParameters { get; init; }
        public required string CallingParameters { get; init; }
    }

    private record VenusLeafApiInfo
    {
        public required LeafTypeInfo LeafTypeInfo { get; init; }
        public required LeafInitializationMethodInfo? LeafInitializationMethodInfo { get; init; }
    }

    private const string MethodParameterSeparator = ",\n        ";
    private const string Namespace = "VenusRootLoader.SourceGenerators";
    private const string ExposeFromVenusAttribute = "ExposeFromVenusAttribute";
    private const string LeafInitializeFromNewAttribute = "LeafInitializeFromNewAttribute";
    private const string MapEntityInitializeFromNewAttributeName = "MapEntityInitializeFromNewAttribute";

    private const string AttributeSourceCode =
        $$"""
          // <auto-generated />

          #nullable enable
          namespace {{Namespace}};

          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Class)]
          internal class {{ExposeFromVenusAttribute}} : System.Attribute
          {
              internal bool WithRegisterMethod { get; init; }
              internal Type? OrderAfter { get; init; } = null;

              internal {{ExposeFromVenusAttribute}}(Type? orderAfter = null, bool withRegisterMethod = true)
              {
                  OrderAfter = orderAfter;
                  WithRegisterMethod = withRegisterMethod;
              }
          }

          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{LeafInitializeFromNewAttribute}} : System.Attribute
          {
          }

          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{MapEntityInitializeFromNewAttributeName}} : System.Attribute
          {
          }
          """;

    private const string VenusSourceCodeTemplate =
        """
        // <auto-generated />

        #nullable enable
        namespace VenusRootLoader.Api;

        public partial class Venus
        {
        {{methods}}
        }
        """;

    private const string MapEntityRegisterMethodTemplate =
        """
            public {{leafTypeName}} Register{{leafTypeNameWithoutLeafSuffix}}(
                string namedId,
                VenusRootLoader.Api.Leaves.MapLeaf map,
                {{initializeMethodParameters}})
            {
                {{leafTypeName}} mapEntity = RegisterMapEntity<{{leafTypeName}}>(namedId, map);
                mapEntity.{{initializeMethodName}}({{initializeMethodCallingParameters}});
                return mapEntity;
            }
        """;

    private const string VenusLeafWithInitializeRegisterMethodTemplate =
        """
            public {{leafTypeName}} Register{{leafTypeNameWithoutLeafSuffix}}(
                string namedId,
                {{initializeMethodParameters}})
            {
                {{leafTypeName}} leaf = VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().RegisterNew(BudId, namedId);
                leaf.{{initializeMethodName}}({{initializeMethodCallingParameters}});
                return leaf;
            }
        """;

    private const string VenusLeafWithoutInitializeRegisterMethodTemplate =
        """
            public {{leafTypeName}} Register{{leafTypeNameWithoutLeafSuffix}}(string namedId)
            {
                return VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().RegisterNew(BudId, namedId);
            }
        """;

    private const string VenusLeafWithtInitializeRegisterOrderedMethodTemplate =
        """
            public {{leafTypeName}} Register{{leafTypeNameWithoutLeafSuffix}}(
                string namedId,
                {{initializeMethodParameters}},
                {{orderAfterTypeName}}? orderAfter,
                int orderPriority)
            {
                {{leafTypeName}} leaf = VenusRootLoader.Registry.RegistryResolver.ResolveWithOrdering<{{leafTypeName}}>().RegisterNewWithOrdering(
                    BudId,
                    namedId,
                    (int?)orderAfter,
                    orderPriority);
                leaf.{{initializeMethodName}}({{initializeMethodCallingParameters}});
                return leaf;
            }
        """;

    private const string VenusLeafWithoutInitializeRegisterOrderedMethodTemplate =
        """
            public {{leafTypeName}} Register{{leafTypeNameWithoutLeafSuffix}}(
                string namedId,
                {{orderAfterTypeName}}? orderAfter,
                int orderPriority)
            {
                return VenusRootLoader.Registry.RegistryResolver.ResolveWithOrdering<{{leafTypeName}}>().RegisterNewWithOrdering(
                    BudId,
                    namedId,
                    (int?)orderAfter,
                    orderPriority);
            }
        """;

    private const string VenusLeafGetMethodsTemplate =
        """
            public {{leafTypeName}} Get{{leafTypeNameWithoutLeafSuffix}}(string creatorId, string namedId)
            {
                return VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().Get(creatorId, namedId);
            }

            public {{leafTypeName}} Get{{leafTypeNameWithoutLeafSuffix}}FromBaseGame(string namedId)
            {
                return VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().Get(Constants.BaseGameCreatorId, namedId);
            }

            public bool TryGet{{leafTypeNameWithoutLeafSuffix}}(string creatorId, string namedId, out {{leafTypeName}}? leaf)
            {
                return VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().TryGet(creatorId, namedId, out leaf);
            }

            public IReadOnlyCollection<{{leafTypeName}}> GetAll{{leafTypeNamePluralizedWithoutLeafSuffix}}()
            {
                return VenusRootLoader.Registry.RegistryResolver.Resolve<{{leafTypeName}}>().GetAll();
            }
        """;

    private const string VenusLeafRegistryApiWithoutInitializeTemplate =
        $$$"""
           {{{VenusLeafWithoutInitializeRegisterMethodTemplate}}}

           {{{VenusLeafGetMethodsTemplate}}}
           """;

    private const string VenusLeafRegistryApiWithInitializationTemplate =
        $$$"""
           {{{VenusLeafWithInitializeRegisterMethodTemplate}}}

           {{{VenusLeafGetMethodsTemplate}}}
           """;

    private const string VenusLeafRegistryApiWithOrderingWithoutInitializeTemplate =
        $$$"""
           {{{VenusLeafWithoutInitializeRegisterOrderedMethodTemplate}}}

           {{{VenusLeafGetMethodsTemplate}}}
           """;

    private const string VenusLeafRegistryApiWithOrderingWithInitializeTemplate =
        $$$"""
           {{{VenusLeafWithtInitializeRegisterOrderedMethodTemplate}}}

           {{{VenusLeafGetMethodsTemplate}}}
           """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                $"{ExposeFromVenusAttribute}.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        IncrementalValuesProvider<LeafTypeInfo> providerLeafType = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{ExposeFromVenusAttribute}",
                DummyPredicate,
                TransformLeafType);

        IncrementalValueProvider<ImmutableArray<LeafInitializationMethodInfo>> providerLeafInitializationMethod =
            context
                .SyntaxProvider
                .ForAttributeWithMetadataName(
                    $"{Namespace}.{LeafInitializeFromNewAttribute}",
                    DummyPredicate,
                    TransformLeafInitializationMethod)
                .Collect();

        IncrementalValueProvider<ImmutableArray<VenusLeafApiInfo>> finalProvider =
            providerLeafType.Combine(providerLeafInitializationMethod)
                .Select((x, _) => new VenusLeafApiInfo
                {
                    LeafTypeInfo = x.Left,
                    LeafInitializationMethodInfo = x.Right.SingleOrDefault(y => y.LeafTypeName == x.Left.LeafTypeName)
                })
                .Collect();

        IncrementalValueProvider<ImmutableArray<LeafInitializationMethodInfo>> providerMapEntityInitialization = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{MapEntityInitializeFromNewAttributeName}",
                DummyPredicate,
                TransformLeafInitializationMethod)
            .Collect();

        context.RegisterSourceOutput(finalProvider, GenerateCode);
        context.RegisterSourceOutput(providerMapEntityInitialization, GenerateCodeMapEntityRegistration);
    }

    private static bool DummyPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken) => true;

    private static LeafTypeInfo TransformLeafType(
        GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        INamedTypeSymbol leafTypeSymbol =
            (INamedTypeSymbol)syntaxContext.SemanticModel.GetDeclaredSymbol(
                syntaxContext.TargetNode,
                cancellationToken)!;

        INamedTypeSymbol? orderAfterTypeSymbol = null;
        TypedConstant orderAfterArgument = syntaxContext.Attributes.Single().ConstructorArguments[0];
        TypedConstant withRegisterMethodArgument = syntaxContext.Attributes.Single().ConstructorArguments[1];
        if (!orderAfterArgument.IsNull)
            orderAfterTypeSymbol = (INamedTypeSymbol)orderAfterArgument.Value!;

        return new()
        {
            LeafTypeName = leafTypeSymbol.Name,
            LeafTypeDisplayString = leafTypeSymbol.ToDisplayString(),
            OrderAfterTypeName = orderAfterTypeSymbol?.ToDisplayString(),
            WithRegisterMethod = (bool)withRegisterMethodArgument.Value!
        };
    }

    private static LeafInitializationMethodInfo TransformLeafInitializationMethod(
        GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        IMethodSymbol initializeMethodSymbol =
            (IMethodSymbol)syntaxContext.SemanticModel.GetDeclaredSymbol(
                syntaxContext.TargetNode,
                cancellationToken)!;

        return new()
        {
            LeafTypeName = initializeMethodSymbol.ContainingType.Name,
            LeafTypeDisplayString = initializeMethodSymbol.ContainingType.ToDisplayString(),
            MethodName = initializeMethodSymbol.Name,
            MethodParameters = BuildMethodSignatureParameters(initializeMethodSymbol),
            CallingParameters = BuildMethodCallingParameters(initializeMethodSymbol)
        };
    }

    private static string BuildMethodSignatureParameters(IMethodSymbol registerMethodSymbol)
    {
        return string.Join(MethodParameterSeparator, registerMethodSymbol.Parameters.Select(p => p.ToDisplayString()));
    }

    private static string BuildMethodCallingParameters(IMethodSymbol symbolMethod)
    {
        return string.Join(", ", symbolMethod.Parameters.Select(p => p.Name));
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<VenusLeafApiInfo> leafTypeInfos)
    {
        foreach (VenusLeafApiInfo info in leafTypeInfos)
        {
            string venusSourceCode = VenusSourceCodeTemplate.Replace(
                "{{methods}}",
                BuildVenusRegistryApiMethodsSourceCode(info));
            context.AddSource(
                $"Venus{info.LeafTypeInfo.LeafTypeName}.g.cs",
                SourceText.From(venusSourceCode, Encoding.UTF8));
        }
    }

    private static string BuildVenusRegistryApiMethodsSourceCode(VenusLeafApiInfo venusLeafApiInfo)
    {
        string template = venusLeafApiInfo switch
        {
            { LeafTypeInfo.WithRegisterMethod: false } => VenusLeafGetMethodsTemplate,
            { LeafTypeInfo.OrderAfterTypeName: not null, LeafInitializationMethodInfo: null } =>
                VenusLeafRegistryApiWithOrderingWithoutInitializeTemplate,
            { LeafTypeInfo.OrderAfterTypeName: not null, LeafInitializationMethodInfo: not null } =>
                VenusLeafRegistryApiWithOrderingWithInitializeTemplate,
            _ => venusLeafApiInfo.LeafInitializationMethodInfo is null
                ? VenusLeafRegistryApiWithoutInitializeTemplate
                : VenusLeafRegistryApiWithInitializationTemplate
        };

        StringBuilder sb = new(template);
        sb.Replace("{{orderAfterTypeName}}", venusLeafApiInfo.LeafTypeInfo.OrderAfterTypeName ?? "");

        FillCommonInfo(
            sb,
            venusLeafApiInfo.LeafTypeInfo.LeafTypeName,
            venusLeafApiInfo.LeafTypeInfo.LeafTypeDisplayString,
            venusLeafApiInfo.LeafInitializationMethodInfo);

        return sb.ToString();
    }

    private static void GenerateCodeMapEntityRegistration(
        SourceProductionContext context,
        ImmutableArray<LeafInitializationMethodInfo> mapEntityInitializationInfos)
    {
        string venusSourceCode = VenusSourceCodeTemplate.Replace(
            "{{methods}}",
            string.Join("\n\n", mapEntityInitializationInfos.Select(BuildVenusMapEntityRegisterMethodSourceCode)));

        context.AddSource("VenusMapEntityRegistration.g.cs", SourceText.From(venusSourceCode, Encoding.UTF8));
    }

    private static string BuildVenusMapEntityRegisterMethodSourceCode(
        LeafInitializationMethodInfo venusMapEntityRegisterMethodInfo)
    {
        StringBuilder sb = new(MapEntityRegisterMethodTemplate);

        FillCommonInfo(
            sb,
            venusMapEntityRegisterMethodInfo.LeafTypeName,
            venusMapEntityRegisterMethodInfo.LeafTypeDisplayString,
            venusMapEntityRegisterMethodInfo);

        return sb.ToString();
    }

    private static void FillCommonInfo(
        StringBuilder sb,
        string leafTypeName,
        string leafTypeDisplayString,
        LeafInitializationMethodInfo? venusMapEntityRegisterMethodInfo)
    {
        string typeNameWithoutLeafSuffix = leafTypeName[..^4];
        sb.Replace("{{leafTypeName}}", leafTypeDisplayString);
        sb.Replace("{{leafTypeNameWithoutLeafSuffix}}", typeNameWithoutLeafSuffix);
        sb.Replace("{{leafTypeNamePluralizedWithoutLeafSuffix}}", typeNameWithoutLeafSuffix.Pluralize());
        sb.Replace("{{initializeMethodParameters}}", venusMapEntityRegisterMethodInfo?.MethodParameters ?? "");
        sb.Replace("{{initializeMethodName}}", venusMapEntityRegisterMethodInfo?.MethodName ?? "");
        sb.Replace("{{initializeMethodCallingParameters}}", venusMapEntityRegisterMethodInfo?.CallingParameters ?? "");
    }
}