using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace VenusRootLoader.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class VenusMapEntityRegisterMethodsSourceGenerator : IIncrementalGenerator
{
    private record BaseRegisterMethodInfo
    {
        public required string Name { get; init; }
        public required string MethodParameters { get; init; }
        public required string CallingParameters { get; init; }
    }

    private record MapEntityInitializationInfo
    {
        public required string MapEntityTypeName { get; init; }
        public required string MapEntityDisplayString { get; init; }
        public required string InitializeMethodName { get; init; }
        public required string InitializeMethodParameters { get; init; }
        public required string InitializeMethodCallingParameters { get; init; }
    }

    private record VenusMapEntityRegisterMethodInfo
    {
        public required string MapEntityTypeName { get; init; }
        public required string MapEntityDisplayString { get; init; }
        public required string MethodParameters { get; init; }
        public required string MapEntityBaseRegisterMethodName { get; init; }
        public required string MapEntityBaseRegisterMethodCallingParameters { get; init; }
        public required string MapEntityInitializeFromNewMethodName { get; init; }
        public required string MapEntityInitializeFromNewMethodCallingParameters { get; init; }
    }

    private const string MethodParameterSeparator = ",\n        ";
    private const string Namespace = "VenusRootLoader.SourceGenerators";
    private const string MapEntityInitializeFromNewAttributeName = "MapEntityInitializeFromNewAttribute";
    private const string MapEntityRegisterMethodAttributeName = "MapEntityRegisterMethodAttribute";

    private const string AttributeSourceCode =
        $$"""
          // <auto-generated/>

          namespace {{Namespace}};

          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{MapEntityInitializeFromNewAttributeName}} : System.Attribute
          {
          }
          
          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{MapEntityRegisterMethodAttributeName}} : System.Attribute
          {
          }
          """;

    private const string VenusSourceCodeTemplate =
        """
        // <auto-generated/>

        namespace VenusRootLoader.Api;

        public partial class Venus
        {
        {{methods}}
        }
        """;

    private const string MapEntityRegisterMethodTemplate =
        """
            public {{mapEntityTypeName}} Register{{mapEntityTypeNameWithoutLeafSuffix}}(
                {{methodParameters}})
            {
                {{mapEntityTypeName}} mapEntity = {{mapEntityRegisterMethodName}}<{{mapEntityTypeName}}>({{mapEntityRegisterMethodParameters}});
                mapEntity.{{mapEntityInitializeFromNewMethodName}}({{mapEntityInitializeFromNewMethodParameters}});
                return mapEntity;
            }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                $"{MapEntityInitializeFromNewAttributeName}.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        IncrementalValueProvider<BaseRegisterMethodInfo> providerRegisterMethod = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{MapEntityRegisterMethodAttributeName}",
                DummyPredicate,
                TransformRegisterMethod)
            .Collect()
            .Select((x, _) => x.Single());
        IncrementalValuesProvider<MapEntityInitializationInfo> providerMapEntityInitialization = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{MapEntityInitializeFromNewAttributeName}",
                DummyPredicate,
                TransformMapEntityInitializeFromNewMethod);

        IncrementalValueProvider<ImmutableArray<VenusMapEntityRegisterMethodInfo>> finalProvider =
            providerRegisterMethod
                .Combine(providerMapEntityInitialization.Collect())
                .SelectMany((combined, _) => combined.Right.Select(mapEntityInitializationInfo =>
                    MergeProviderValues(combined.Left, mapEntityInitializationInfo)))
                .Collect();

        context.RegisterSourceOutput(finalProvider, GenerateCode);
    }

    private static bool DummyPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken) => true;

    private static BaseRegisterMethodInfo TransformRegisterMethod(
        GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        IMethodSymbol registerMethodSymbol =
            (IMethodSymbol)syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.TargetNode, cancellationToken)!;
        return new()
        {
            Name = registerMethodSymbol.Name,
            MethodParameters = BuildMethodSignatureParameters(registerMethodSymbol),
            CallingParameters = BuildMethodCallingParameters(registerMethodSymbol)
        };
    }

    private static MapEntityInitializationInfo TransformMapEntityInitializeFromNewMethod(
        GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        IMethodSymbol initializeFromNewSymbol =
            (IMethodSymbol)syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.TargetNode, cancellationToken)!;

        return new()
        {
            MapEntityTypeName = initializeFromNewSymbol.ContainingType.Name,
            MapEntityDisplayString = initializeFromNewSymbol.ContainingType.ToDisplayString(),
            InitializeMethodName = initializeFromNewSymbol.Name,
            InitializeMethodParameters = BuildMethodSignatureParameters(initializeFromNewSymbol),
            InitializeMethodCallingParameters = BuildMethodCallingParameters(initializeFromNewSymbol),
        };
    }

    private static string BuildMethodSignatureParameters(IMethodSymbol registerMethodSymbol)
    {
        return string.Join(MethodParameterSeparator, registerMethodSymbol.Parameters.Select(p => p.ToDisplayString()));
    }

    private static string BuildMethodCallingParameters(IMethodSymbol symbolMethod)
    {
        return string.Join(", ", symbolMethod.Parameters.Select(p => p.Name));
    }

    private static VenusMapEntityRegisterMethodInfo MergeProviderValues(
        BaseRegisterMethodInfo registerProvider,
        MapEntityInitializationInfo mapEntityInitializationInfo)
    {
        StringBuilder sb = new();
        sb.Append(registerProvider.MethodParameters);
        if (!string.IsNullOrWhiteSpace(mapEntityInitializationInfo.InitializeMethodParameters))
        {
            sb.Append(MethodParameterSeparator);
            sb.Append(mapEntityInitializationInfo.InitializeMethodParameters);
        }

        string methodParameters = sb.ToString();

        return new VenusMapEntityRegisterMethodInfo
        {
            MapEntityTypeName = mapEntityInitializationInfo.MapEntityTypeName,
            MapEntityDisplayString = mapEntityInitializationInfo.MapEntityDisplayString,
            MethodParameters = methodParameters,
            MapEntityBaseRegisterMethodName = registerProvider.Name,
            MapEntityBaseRegisterMethodCallingParameters = registerProvider.CallingParameters,
            MapEntityInitializeFromNewMethodName = mapEntityInitializationInfo.InitializeMethodName,
            MapEntityInitializeFromNewMethodCallingParameters =
                mapEntityInitializationInfo.InitializeMethodCallingParameters
        };
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<VenusMapEntityRegisterMethodInfo> registerMethodInfos)
    {
        string venusSourceCode = VenusSourceCodeTemplate.Replace(
            "{{methods}}",
            string.Join("\n\n", registerMethodInfos.Select(BuildVenusMapEntityRegisterMethodSourceCode)));

        context.AddSource("VenusMapEntity.g.cs", SourceText.From(venusSourceCode, Encoding.UTF8));
    }

    private static string BuildVenusMapEntityRegisterMethodSourceCode(
        VenusMapEntityRegisterMethodInfo venusMapEntityRegisterMethodInfo)
    {
        StringBuilder sb = new(MapEntityRegisterMethodTemplate);
        sb.Replace("{{mapEntityTypeName}}", venusMapEntityRegisterMethodInfo.MapEntityDisplayString);
        sb.Replace("{{mapEntityTypeNameWithoutLeafSuffix}}", venusMapEntityRegisterMethodInfo.MapEntityTypeName[..^4]);
        sb.Replace("{{methodParameters}}", venusMapEntityRegisterMethodInfo.MethodParameters);
        sb.Replace("{{mapEntityRegisterMethodName}}", venusMapEntityRegisterMethodInfo.MapEntityBaseRegisterMethodName);
        sb.Replace(
            "{{mapEntityRegisterMethodParameters}}",
            venusMapEntityRegisterMethodInfo.MapEntityBaseRegisterMethodCallingParameters);
        sb.Replace(
            "{{mapEntityInitializeFromNewMethodName}}",
            venusMapEntityRegisterMethodInfo.MapEntityInitializeFromNewMethodName);
        sb.Replace(
            "{{mapEntityInitializeFromNewMethodParameters}}",
            venusMapEntityRegisterMethodInfo.MapEntityInitializeFromNewMethodCallingParameters);
        return sb.ToString();
    }
}