<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <LangVersion>7.3</LangVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="$(ModifiedGameAssemblyPath)" Publicize="true" Strip="true"/>
        <Reference Include="$(GameDataManagedPath)/UnityEngine*.dll" Publicize="true" Strip="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../../Runtime/**/*.cs" LinkBase="Runtime"/>
    </ItemGroup>
</Project>
