using Humanizer;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace VenusRootLoader.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class VenusLeafRegistryApiSourceGenerator : IIncrementalGenerator
{
    private record LeafTypeInfo
    {
        public required string LeafTypeName { get; init; }
        public required string LeafTypeDisplayString { get; init; }
    }

    private const string Namespace = "VenusRootLoader.SourceGenerators";
    private const string ExposeFromVenusAttribute = "ExposeFromVenusAttribute";

    private const string AttributeSourceCode =
        $$"""
          // <auto-generated/>

          namespace {{Namespace}};

          [Microsoft.CodeAnalysis.EmbeddedAttribute]
          [System.AttributeUsage(System.AttributeTargets.Class)]
          internal class {{ExposeFromVenusAttribute}} : System.Attribute
          {
          }
          """;

    private const string VenusSourceCodeTemplate =
        """
        // <auto-generated/>

        namespace VenusRootLoader.Api;

        public partial class Venus
        {
        {{methods}}
        }
        """;

    private const string VenusLeafRegistryApiTemplate =
        """
            public {{leafTypeName}} Register{{leafEntityTypeNameWithoutLeafSuffix}}(string namedId)
            {
                return RegistryResolver.Resolve<{{leafTypeName}}>().RegisterNew(BudId, namedId);
            }

            public {{leafTypeName}} Get{{leafEntityTypeNameWithoutLeafSuffix}}(string creatorId, string namedId)
            {
                return RegistryResolver.Resolve<{{leafTypeName}}>().Get(creatorId, namedId);
            }

            public IReadOnlyCollection<{{leafTypeName}}> GetAll{{leafEntityTypeNamePluralizedWithoutLeafSuffix}}()
            {
                return RegistryResolver.Resolve<{{leafTypeName}}>().GetAll();
            }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                $"{ExposeFromVenusAttribute}.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        IncrementalValueProvider<ImmutableArray<LeafTypeInfo>> provider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{ExposeFromVenusAttribute}",
                DummyPredicate,
                TransformLeafType)
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static bool DummyPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken) => true;

    private static LeafTypeInfo TransformLeafType(
        GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        INamedTypeSymbol leafTypeSymbol =
            (INamedTypeSymbol)syntaxContext.SemanticModel.GetDeclaredSymbol(
                syntaxContext.TargetNode,
                cancellationToken)!;
        return new()
        {
            LeafTypeName = leafTypeSymbol.Name,
            LeafTypeDisplayString = leafTypeSymbol.ToDisplayString()
        };
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<LeafTypeInfo> leafTypeInfos)
    {
        string venusSourceCode = VenusSourceCodeTemplate.Replace(
            "{{methods}}",
            string.Join("\n\n", leafTypeInfos.Select(BuildVenusRegistryApiMethodsSourceCode)));

        context.AddSource("VenusLeafRegistryApi.g.cs", SourceText.From(venusSourceCode, Encoding.UTF8));
    }

    private static string BuildVenusRegistryApiMethodsSourceCode(LeafTypeInfo leafTypeInfo)
    {
        string leafTypeNameWithoutLeafSuffix = leafTypeInfo.LeafTypeName[..^4];

        StringBuilder sb = new(VenusLeafRegistryApiTemplate);
        sb.Replace("{{leafTypeName}}", leafTypeInfo.LeafTypeDisplayString);
        sb.Replace("{{leafEntityTypeNameWithoutLeafSuffix}}", leafTypeNameWithoutLeafSuffix);
        sb.Replace("{{leafEntityTypeNamePluralizedWithoutLeafSuffix}}", leafTypeNameWithoutLeafSuffix.Pluralize());
        return sb.ToString();
    }
}