using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VenusRootLoader.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class VenusMapEntityRegisterMethodsSourceGenerator : IIncrementalGenerator
{
    private record struct RegisterMethodInfo
    {
        public required INamedTypeSymbol MapEntityTypeName { get; init; }
        public required IMethodSymbol MapEntityRegisterMethod { get; init; }
        public required IMethodSymbol MapEntityInitializeFromNewMethod { get; init; }
    }

    private const string Namespace = "VenusRootLoader.SourceGenerators";
    private const string MapEntityInitializeFromNewAttributeName = "MapEntityInitializeFromNewAttribute";
    private const string MapEntityRegisterMethodAttributeName = "MapEntityRegisterMethodAttribute";

    private const string AttributeSourceCode =
        $$"""
          // <auto-generated/>

          namespace {{Namespace}};

          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{MapEntityInitializeFromNewAttributeName}} : System.Attribute
          {
          }

          [System.AttributeUsage(System.AttributeTargets.Method)]
          internal class {{MapEntityRegisterMethodAttributeName}} : System.Attribute
          {
          }
          """;

    private const string VenusSourceCodeTemplate =
        """
        // <auto-generated/>

        namespace VenusRootLoader.Api;

        public partial class Venus
        {
        {{methods}}
        }
        """;

    private const string MapEntityRegisterMethodTemplate =
        """
            public {{mapEntityTypeName}} Register{{mapEntityTypeNameWithoutLeafSuffix}}(
                {{methodParameters}})
            {
                {{mapEntityTypeName}} mapEntity = {{mapEntityRegisterMethodName}}<{{mapEntityTypeName}}>({{mapEntityRegisterMethodParameters}});
                mapEntity.{{mapEntityInitializeFromNewMethodName}}({{mapEntityInitializeFromNewMethodParameters}});
                return mapEntity;
            }
        """;

    private static string BuildMapEntityRegisterMethodSourceCode(RegisterMethodInfo registerMethodInfo)
    {
        StringBuilder sb = new(MapEntityRegisterMethodTemplate);
        sb.Replace("{{mapEntityTypeName}}", registerMethodInfo.MapEntityTypeName.ToDisplayString());
        sb.Replace("{{mapEntityTypeNameWithoutLeafSuffix}}", registerMethodInfo.MapEntityTypeName.Name[..^4]);
        sb.Replace(
            "{{methodParameters}}",
            BuildSignatureMethodParametersFromMultiple(
                [registerMethodInfo.MapEntityRegisterMethod, registerMethodInfo.MapEntityInitializeFromNewMethod]));
        sb.Replace("{{mapEntityRegisterMethodName}}", registerMethodInfo.MapEntityRegisterMethod.Name);
        sb.Replace(
            "{{mapEntityRegisterMethodParameters}}",
            BuildMethodCallingParametersFromOne(registerMethodInfo.MapEntityRegisterMethod));
        sb.Replace(
            "{{mapEntityInitializeFromNewMethodName}}",
            registerMethodInfo.MapEntityInitializeFromNewMethod.Name);
        sb.Replace(
            "{{mapEntityInitializeFromNewMethodParameters}}",
            BuildMethodCallingParametersFromOne(registerMethodInfo.MapEntityInitializeFromNewMethod));
        return sb.ToString();
    }

    private static string BuildSignatureMethodParametersFromMultiple(List<IMethodSymbol> symbolMethods)
    {
        IEnumerable<string> parameters = symbolMethods
            .SelectMany(m => m.Parameters)
            .Select(p => p.ToDisplayString());
        return string.Join(",\n        ", parameters);
    }

    private static string BuildMethodCallingParametersFromOne(IMethodSymbol symbolMethod)
    {
        IEnumerable<string> parameters = symbolMethod.Parameters.Select(p => p.Name);
        return string.Join(", ", parameters);
    }

    private static string BuildVenusSourceCode(List<RegisterMethodInfo> registerMethods)
    {
        StringBuilder sb = new(VenusSourceCodeTemplate);
        sb.Replace(
            "{{methods}}",
            string.Join("\n\n", registerMethods.Select(BuildMapEntityRegisterMethodSourceCode)));
        return sb.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{MapEntityInitializeFromNewAttributeName}.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        IncrementalValuesProvider<MethodDeclarationSyntax> provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{MapEntityInitializeFromNewAttributeName}",
                DummyPredicate,
                (syntaxContext, _) => (MethodDeclarationSyntax)syntaxContext.TargetNode);
        IncrementalValueProvider<MethodDeclarationSyntax> provider2 = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{MapEntityRegisterMethodAttributeName}",
                DummyPredicate,
                (syntaxContext, _) => (MethodDeclarationSyntax)syntaxContext.TargetNode)
            .Collect()
            .Select((x, _) => x.Single());

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(provider.Collect()).Combine(provider2),
            (ctx, t) => GenerateCode(ctx, t.Left.Left, t.Left.Right, t.Right));
    }

    private static bool DummyPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken) => true;

    private static void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<MethodDeclarationSyntax> mapEntityInitializeFromNewDeclarations,
        MethodDeclarationSyntax registerMethodDeclaration)
    {
        List<RegisterMethodInfo> registerMethodInfos = new();
        SemanticModel semanticModelRegisterMethod = compilation.GetSemanticModel(registerMethodDeclaration.SyntaxTree);
        IMethodSymbol registerMethodSymbol =
            (IMethodSymbol)semanticModelRegisterMethod.GetDeclaredSymbol(registerMethodDeclaration)!;

        foreach (MethodDeclarationSyntax initializeFromNewDeclaration in mapEntityInitializeFromNewDeclarations)
        {
            SemanticModel semanticModelInitializeFromNewMethod =
                compilation.GetSemanticModel(initializeFromNewDeclaration.SyntaxTree);
            IMethodSymbol initializeFromNewSymbol =
                (IMethodSymbol)semanticModelInitializeFromNewMethod.GetDeclaredSymbol(initializeFromNewDeclaration)!;

            registerMethodInfos.Add(
                new()
                {
                    MapEntityTypeName = initializeFromNewSymbol.ContainingType,
                    MapEntityRegisterMethod = registerMethodSymbol,
                    MapEntityInitializeFromNewMethod = initializeFromNewSymbol,
                });
        }

        context.AddSource(
            "VenusMapEntity.g.cs",
            SourceText.From(BuildVenusSourceCode(registerMethodInfos), Encoding.UTF8));
    }
}