namespace VenusRootLoader.Unity.Runtime.Enums
{
    public enum Areas
    {
        BugariaOutskirts,
        BugariaCity,
        Snakemouth,
        Desert,
        GoldenHills,
        GoldenWay,
        GoldenSettlement,
        BarrenLands,
        FarGrasslands,
        WildGrasslands,
        DefiantRoot,
        SandCastle,
        Beehive,
        HoneyFactory,
        RubberPrison,
        GiantLair,
        MetalLake,
        MetalIsland,
        TermiteCity,
        WaspKingdom,
        BanditHideout,
        StreamMountain,
        ChomperCaves,
        FishingVillage,
        UpperSnakemouth
    }
}