name: .NET CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1.8"
      - name: Add LLVM to path
        run: echo "$GITHUB_WORKSPACE\$env:LLVM_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Check environment
        run: |
          dotnet --version
          clang-cl -v
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1.8"
      - name: Add LLVM to path
        run: echo "$LLVM_PATH/bin" >> $GITHUB_PATH
      - name: Download xwin
        id: xwin
        uses: robinraju/release-downloader@v1
        with:
          repository: 'Jake-Shadle/xwin'
          latest: true
          fileName: '*x86_64-unknown-linux-musl.tar.gz'
          out-file-path: 'xwin'
          extract: true
      - name: Add xwin to path
        run: echo "$GITHUB_WORKSPACE/xwin/$(basename -s .tar.gz ${{ fromJson(steps.xwin.outputs.downloaded_files)[0] }})" >> $GITHUB_PATH
      - name: Install mono
        run: |
          sudo apt install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo chmod +r /usr/share/keyrings/mono-official-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-devel
      - name: Check environment
        run: |
          dotnet --version
          xwin -V
          clang-cl -v
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
